name: ci
on: [push]
jobs:

  license:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: checking license on source code
        run: make license/check


  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: linting code
        run: make lint

  build_test:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-10.15"] # maybe in the future: windows-2019
        go: ["1.17"]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: make test
        run: make test

      - name: make build
        run: make build
